// src/components/Features.tsx
const features = [
  {
    icon: "⚡",
    title: "Lightning Fast Setup",
    description: "Get your Whop store live in under 5 minutes. No coding, no hassle, just pure results."
  },
  {
    icon: "🎨",
    title: "Beautiful Designs",
    description: "Professionally crafted templates that convert. Every pixel optimized for maximum sales."
  },
  {
    icon: "📱",
    title: "Mobile Optimized",
    description: "Perfect on every device. Your customers get a seamless experience anywhere."
  },
  {
    icon: "🔒",
    title: "Secure & Reliable",
    description: "Built with best practices. Your store is safe, secure, and always available."
  },
  {
    icon: "🚀",
    title: "SEO Optimized",
    description: "Rank higher on Google. Our templates are built for maximum visibility."
  },
  {
    icon: "💰",
    title: "Conversion Focused",
    description: "Every element designed to sell. Turn visitors into paying customers."
  }
];

export default function Features() {
  return (
    <section id="features" className="py-20 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <h2 className="text-base font-semibold text-purple-400">Features</h2>
          <p className="mt-2 text-4xl font-bold tracking-tight sm:text-5xl">
            Everything you need to succeed
          </p>
          <p className="mx-auto mt-4 max-w-2xl text-lg text-gray-400">
            Our templates come packed with features that help you launch and grow your Whop business.
          </p>
        </div>

        <div className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <div key={feature.title} className="group relative rounded-2xl border border-gray-800 bg-gray-900/50 p-8 transition-all hover:border-purple-500/50 hover:bg-gray-900">
              <div className="mb-4 text-4xl">{feature.icon}</div>
              <h3 className="mb-2 text-xl font-semibold text-white">{feature.title}</h3>
              <p className="text-gray-400">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// src/lib/components/Features.svelte
<script lang="ts">
	const features = [
		{
			icon: "📚",
			title: "Comprehensive Guides",
			description: "Step-by-step guides covering everything from idea validation to scaling your SaaS business."
		},
		{
			icon: "🎯",
			title: "Market Research Tools",
			description: "Free templates and frameworks to help you understand your target market and competition."
		},
		{
			icon: "💡",
			title: "Startup Templates",
			description: "Ready-to-use templates for business plans, pitch decks, and financial projections."
		},
		{
			icon: "🔧",
			title: "Tech Stack Recommendations",
			description: "Expert recommendations on the best tools and technologies for your SaaS."
		},
		{
			icon: "📊",
			title: "Growth Strategies",
			description: "Proven strategies and tactics to acquire customers and grow your revenue."
		},
		{
			icon: "🤝",
			title: "Community Access",
			description: "Join thousands of SaaS founders sharing insights and supporting each other."
		}
	];
</script>

<section id="features" class="py-20 sm:py-32">
	<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<div class="text-center">
			<h2 class="text-base font-semibold text-purple-400">What You'll Get</h2>
			<p class="mt-2 text-4xl font-bold tracking-tight sm:text-5xl">
				Everything you need to succeed
			</p>
			<p class="mx-auto mt-4 max-w-2xl text-lg text-gray-400">
				Access a complete library of resources designed to help you at every stage of your SaaS journey.
			</p>
		</div>

		<div class="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
			{#each features as feature}
				<div class="group relative rounded-2xl border border-gray-800 bg-gray-900/50 p-8 transition-all hover:border-purple-500/50 hover:bg-gray-900">
					<div class="mb-4 text-4xl">{feature.icon}</div>
					<h3 class="mb-2 text-xl font-semibold text-white">{feature.title}</h3>
					<p class="text-gray-400">{feature.description}</p>
				</div>
			{/each}
		</div>
	</div>
</section>
